"""Add User model and relationships

Revision ID: 9111ec848d13
Revises: 679f33375822
Create Date: 2025-11-09 16:08:49.349362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9111ec848d13'
down_revision: Union[str, Sequence[str], None] = '679f33375822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('inbody_records', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_inbody_records_date'), table_name='inbody_records')
    op.create_index(op.f('ix_inbody_records_date'), 'inbody_records', ['date'], unique=False)
    op.create_unique_constraint('_owner_date_uc', 'inbody_records', ['owner_id', 'date'])
    op.create_foreign_key(None, 'inbody_records', 'users', ['owner_id'], ['id'])
    op.add_column('workout_logs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout_logs', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_logs', type_='foreignkey')
    op.drop_column('workout_logs', 'owner_id')
    op.drop_constraint(None, 'inbody_records', type_='foreignkey')
    op.drop_constraint('_owner_date_uc', 'inbody_records', type_='unique')
    op.drop_index(op.f('ix_inbody_records_date'), table_name='inbody_records')
    op.create_index(op.f('ix_inbody_records_date'), 'inbody_records', ['date'], unique=True)
    op.drop_column('inbody_records', 'owner_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
